### ISSUE TITLE
Latest tag won't start

### ISSUE THREAD

**Issue by jaredlockhart** [mozilla/remote-settings#368]
The latest tag pushed to dockerhub here:

https://hub.docker.com/layers/mozilla/remote-settings/latest/images/sha256-96f0e2d2ef6afa2748b1b987f2aa910b724b0b1c4e9e10716890d23d391edc5d?context=explore

Won't start in my local or CI:

![image](https://user-images.githubusercontent.com/119884/217306936-fef23adb-d7e6-452c-be93-48739542e74e.png)

I don't see any update instructions in the tags:

https://github.com/mozilla/remote-settings/tags

**Comment by grahamalama** [comment]
Looks like a file permissions issue in the container.

<details><summary>Traceback</summary>
<p>

```
Traceback (most recent call last):
  File "app.wsgi", line 30, in <module>
    application = main(config.items('DEFAULT'), **dict(config.items('app:main')))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/kinto/__init__.py", line 51, in main
    kinto.core.initialize(config, version=__version__, default_settings=DEFAULT_SETTINGS)
  File "/opt/venv/lib/python3.11/site-packages/kinto/core/initialization.py", line 618, in initialize
    config.include("kinto.core", route_prefix=api_version)
  File "/opt/venv/lib/python3.11/site-packages/pyramid/config/__init__.py", line 666, in include
    c(configurator)
  File "/opt/venv/lib/python3.11/site-packages/kinto/core/__init__.py", line 218, in includeme
    config.include(app)
  File "/opt/venv/lib/python3.11/site-packages/pyramid/config/__init__.py", line 666, in include
    c(configurator)
  File "/opt/venv/lib/python3.11/site-packages/kinto_emailer/__init__.py", line 192, in includeme
    config.include('pyramid_mailer' + ('.debug' if debug else ''))
  File "/opt/venv/lib/python3.11/site-packages/pyramid/config/__init__.py", line 666, in include
    c(configurator)
  File "/opt/venv/lib/python3.11/site-packages/pyramid_mailer/debug.py", line 8, in includeme
    mailer = DebugMailer(path)
             ^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.11/site-packages/pyramid_mailer/mailer.py", line 40, in __init__
    makedirs(top_level_directory)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/app/mail'
```

</p>
</details>
